# This file contains values from Cookiecutter

default_context:
  project_name: "qualifire"
  project_description: "Qualifire PYthon SDK"
  organization: "qualifire-dev"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "qualifire_dev"
  email: "dror@qualifire.ai"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
